### ISSUE TITLE
Support IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by dheid** [ricemery/Assertions2AssertJ#13]
The current version of the "Assertions2AssertJ" plugin is not compatible with IntelliJ IDEA 2023.3. This issue affects users who have upgraded to this latest version and are unable to use the Assertions2AssertJ plugin effectively or at all.

**Comment by ricemery** [comment]
I am currently on vacation. I will take a look at the changes next week.
Thank you very much
