### ISSUE TITLE
Assertions are not converted for nested classes

### ISSUE THREAD

**Issue by tbureck** [ricemery/Assertions2AssertJ#9]
Hi!

When I use the plugin action "Convert Assertions to AssertJ" for the current file, the plugin will only convert the assertions for the top level class test methods, but not for any existing test methods in nested classes.

I've created a test project which you can use to reproduce the issue: https://github.com/tbureck/assertions2assertj-nested-classes

1) Checkout
2) Open in IntelliJ and run said action
3) Assertion in `someTest` will be converted, however not in `NestedTest.nestedTest`

**IntelliJ version:** IntelliJ IDEA 2020.3.2 (Ultimate Edition) Build #IU-203.7148.57, built on January 26, 2021
**Plugin version:** 1.0.05

Best regards

**Comment by ricemery** [comment]
Thank you for the report and the test project.  I was not aware of the @Nested functionality.

**Comment by ricemery** [comment]
Fixed in 1.0.06
